---
- hosts: all
  roles:

  # osx config
  - role: dock
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  #- role: cask_package
  #  tap: caskroom/fonts
  #  package_name: font-source-code-pro

  # cli
  # shell tooling
  - role: git
    git_user_name: Jørgen Orehøj Erichsen
    git_user_email: joe@erichsen.net
  - role: legit
  - role: hub

  ## languages
  - role: rbenv
  - role: cask_package
    package_name: java

  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mysql
  - role: brew_package
    package_name: redis
  
  # gui
  ## text editors
  #- role: cask_package
  #  package_name: atom
